set -e
# indent kommt damit nicht klar ...
C_Dateien_ohne_Formatierung=(
src/gtk/gtkcmclist.c
src/gtk/gtkcmctree.c
src/gtk/gtksctree.c
src/wizard.c
)
C_Dateien_mit_Typen=(
src/account.c
src/action.c
src/addr_compl.c
src/addrbook.c
src/addrcache.c
src/addrclip.c
src/addrcustomattr.c
src/addrduplicates.c
src/addressadd.c
src/addressbook-dbus.c
src/addressbook.c
src/addressbook_foldersel.c
src/addrgather.c
src/addrharvest.c
src/addrindex.c
src/addritem.c
src/addrmerge.c
src/addrquery.c
src/addrselect.c
src/advsearch.c
src/alertpanel.c
src/autofaces.c
src/avatars.c
src/browseldap.c
src/common/claws.c
src/common/codeconv.c
src/common/file-utils.c
src/common/hooks.c
src/common/log.c
src/common/md5.c
src/common/mgutils.c
src/common/passcrypt.c
src/common/pkcs5_pbkdf2.c
src/common/plugin.c
src/common/prefs.c
src/common/progressindicator.c
src/common/proxy.c
src/common/quoted-printable.c
src/common/session.c
src/common/smtp.c
src/common/socket.c
src/common/ssl.c
src/common/ssl_certificate.c
src/common/string_match.c
src/common/stringtable.c
src/common/tags.c
src/common/template.c
src/common/tests/codeconv_test.c
src/common/tests/md5_test.c
src/common/tests/pkcs5_pbkdf2_test.c
src/common/tests/unmime_test.c
src/common/tests/utils_get_serverportfp_from_filename_test.c
src/common/tests/utils_get_uri_part_test.c
src/common/tests/xml_test.c
src/common/unmime.c
src/common/utils.c
src/common/uuencode.c
src/common/w32_reg.c
src/common/xml.c
src/common/xmlprops.c
src/compose.c
src/crash.c
src/customheader.c
src/displayheader.c
src/editaddress.c
src/editaddress_other_attributes_ldap.c
src/editbook.c
src/editgroup.c
src/editjpilot.c
src/editldap.c
src/editldap_basedn.c
src/edittags.c
src/editvcard.c
src/enriched.c
src/entity.c
src/etpan/etpan-ssl.c
src/etpan/etpan-thread-manager.c
src/etpan/imap-thread.c
src/etpan/nntp-thread.c
src/exphtmldlg.c
src/expldifdlg.c
src/export.c
src/exporthtml.c
src/exportldif.c
src/file_checker.c
src/filtering.c
src/folder.c
src/folder_item_prefs.c
src/foldersel.c
src/folderutils.c
src/folderview.c
src/grouplistdialog.c
src/gtk/about.c
src/gtk/colorlabel.c
src/gtk/combobox.c
src/gtk/description_window.c
src/gtk/filesel.c
src/gtk/foldersort.c
src/gtk/gtkaspell.c
src/gtk/gtkshruler.c
src/gtk/gtkunit.c
src/gtk/gtkutils.c
src/gtk/gtkvscrollbutton.c
src/gtk/icon_legend.c
src/gtk/inputdialog.c
src/gtk/logwindow.c
src/gtk/manage_window.c
src/gtk/menu.c
src/gtk/pluginwindow.c
src/gtk/prefswindow.c
src/gtk/progressdialog.c
src/gtk/quicksearch.c
src/gtk/spell_entry.c
src/gtk/sslcertwindow.c
src/gtk/w32_filesel.c
src/headerview.c
src/html.c
src/image_viewer.c
src/imap.c
src/imap_gtk.c
src/import.c
src/importldif.c
src/importmutt.c
src/importpine.c
src/inc.c
src/jpilot.c
src/ldapctrl.c
src/ldaplocate.c
src/ldapquery.c
src/ldapserver.c
src/ldapupdate.c
src/ldaputil.c
src/ldif.c
src/localfolder.c
src/main.c
src/mainwindow.c
src/manual.c
src/matcher.c
src/mbox.c
src/message_search.c
src/messageview.c
src/mh.c
src/mh_gtk.c
src/mimeview.c
src/msgcache.c
src/mutt.c
src/news.c
src/news_gtk.c
src/noticeview.c
src/oauth2.c
src/partial_download.c
src/password.c
src/password_gtk.c
src/passwordstore.c
src/pine.c
src/plugins/acpi_notifier/acpi_notifier.c
src/plugins/address_keeper/address_keeper.c
src/plugins/address_keeper/address_keeper_prefs.c
src/plugins/archive/archiver.c
src/plugins/archive/archiver_gtk.c
src/plugins/archive/archiver_prefs.c
src/plugins/archive/libarchive_archive.c
src/plugins/att_remover/att_remover.c
src/plugins/attachwarner/attachwarner.c
src/plugins/attachwarner/attachwarner_prefs.c
src/plugins/bogofilter/bogofilter.c
src/plugins/bogofilter/bogofilter_gtk.c
src/plugins/bsfilter/bsfilter.c
src/plugins/bsfilter/bsfilter_gtk.c
src/plugins/clamd/clamav_plugin.c
src/plugins/clamd/clamav_plugin_gtk.c
src/plugins/clamd/libclamd/clamd-plugin.c
src/plugins/demo/demo.c
src/plugins/dillo/dillo_prefs.c
src/plugins/dillo/dillo_viewer.c
src/plugins/fancy/fancy_prefs.c
src/plugins/fancy/fancy_viewer.c
src/plugins/fetchinfo/fetchinfo_plugin.c
src/plugins/fetchinfo/fetchinfo_plugin_gtk.c
src/plugins/gdata/cm_gdata_contacts.c
src/plugins/gdata/cm_gdata_prefs.c
src/plugins/gdata/gdata_plugin.c
src/plugins/keyword_warner/keyword_warner.c
src/plugins/keyword_warner/keyword_warner_prefs.c
src/plugins/libravatar/libravatar.c
src/plugins/libravatar/libravatar_cache.c
src/plugins/libravatar/libravatar_federation.c
src/plugins/libravatar/libravatar_image.c
src/plugins/libravatar/libravatar_missing.c
src/plugins/libravatar/libravatar_prefs.c
src/plugins/litehtml_viewer/lh_prefs.c
src/plugins/litehtml_viewer/lh_viewer.c
src/plugins/litehtml_viewer/plugin.c
src/plugins/mailmbox/carray.c
src/plugins/mailmbox/chash.c
src/plugins/mailmbox/clist.c
src/plugins/mailmbox/mailimf.c
src/plugins/mailmbox/mailimf_types.c
src/plugins/mailmbox/mailimf_types_helper.c
src/plugins/mailmbox/mailimf_write.c
src/plugins/mailmbox/maillock.c
src/plugins/mailmbox/mailmbox.c
src/plugins/mailmbox/mailmbox_folder.c
src/plugins/mailmbox/mailmbox_parse.c
src/plugins/mailmbox/mailmbox_types.c
src/plugins/mailmbox/mmapstring.c
src/plugins/mailmbox/plugin.c
src/plugins/mailmbox/plugin_gtk.c
src/plugins/managesieve/managesieve.c
src/plugins/managesieve/sieve_editor.c
src/plugins/managesieve/sieve_manager.c
src/plugins/managesieve/sieve_plugin.c
src/plugins/managesieve/sieve_prefs.c
src/plugins/newmail/newmail.c
src/plugins/notification/gtkhotkey/gtk-hotkey-error.c
src/plugins/notification/gtkhotkey/gtk-hotkey-info.c
src/plugins/notification/gtkhotkey/gtk-hotkey-key-file-registry.c
src/plugins/notification/gtkhotkey/gtk-hotkey-listener.c
src/plugins/notification/gtkhotkey/gtk-hotkey-marshal.c
src/plugins/notification/gtkhotkey/gtk-hotkey-registry.c
src/plugins/notification/gtkhotkey/gtk-hotkey-utils.c
src/plugins/notification/gtkhotkey/gtk-hotkey-x11-listener.c
src/plugins/notification/gtkhotkey/x11/eggaccelerators.c
src/plugins/notification/gtkhotkey/x11/tomboykeybinder.c
src/plugins/notification/notification_banner.c
src/plugins/notification/notification_command.c
src/plugins/notification/notification_core.c
src/plugins/notification/notification_foldercheck.c
src/plugins/notification/notification_hotkeys.c
src/plugins/notification/notification_indicator.c
src/plugins/notification/notification_lcdproc.c
src/plugins/notification/notification_pixbuf.c
src/plugins/notification/notification_plugin.c
src/plugins/notification/notification_popup.c
src/plugins/notification/notification_prefs.c
src/plugins/notification/notification_trayicon.c
src/plugins/pdf_viewer/poppler_viewer.c
src/plugins/perl/perl_gtk.c
src/plugins/perl/perl_plugin.c
src/plugins/pgpcore/autocompletion.c
src/plugins/pgpcore/passphrase.c
src/plugins/pgpcore/pgp_utils.c
src/plugins/pgpcore/pgp_viewer.c
src/plugins/pgpcore/plugin.c
src/plugins/pgpcore/prefs_gpg.c
src/plugins/pgpcore/select-keys.c
src/plugins/pgpcore/sgpgme.c
src/plugins/pgpcore/tests/pgp_utils_test.c
src/plugins/pgpinline/pgpinline.c
src/plugins/pgpinline/plugin.c
src/plugins/pgpmime/pgpmime.c
src/plugins/pgpmime/plugin.c
src/plugins/python/accounttype.c
src/plugins/python/clawsmailmodule.c
src/plugins/python/composewindowtype.c
src/plugins/python/folderpropertiestype.c
src/plugins/python/foldertype.c
src/plugins/python/mailboxtype.c
src/plugins/python/messageinfotype.c
src/plugins/python/nodetype.c
src/plugins/python/python-hooks.c
src/plugins/python/python-shell.c
src/plugins/python/python_plugin.c
src/plugins/python/python_prefs.c
src/plugins/rssyl/libfeed/date.c
src/plugins/rssyl/libfeed/feed.c
src/plugins/rssyl/libfeed/feeditem.c
src/plugins/rssyl/libfeed/feeditemenclosure.c
src/plugins/rssyl/libfeed/parser.c
src/plugins/rssyl/libfeed/parser_atom10.c
src/plugins/rssyl/libfeed/parser_opml.c
src/plugins/rssyl/libfeed/parser_rdf.c
src/plugins/rssyl/libfeed/parser_rss20.c
src/plugins/rssyl/libfeed/tests/date_test.c
src/plugins/rssyl/libfeed/tests/feed_test.c
src/plugins/rssyl/old_feeds.c
src/plugins/rssyl/opml_export.c
src/plugins/rssyl/opml_import.c
src/plugins/rssyl/parse822.c
src/plugins/rssyl/plugin.c
src/plugins/rssyl/rssyl.c
src/plugins/rssyl/rssyl_add_item.c
src/plugins/rssyl/rssyl_cb_menu.c
src/plugins/rssyl/rssyl_deleted.c
src/plugins/rssyl/rssyl_feed.c
src/plugins/rssyl/rssyl_feed_props.c
src/plugins/rssyl/rssyl_gtk.c
src/plugins/rssyl/rssyl_parse_feed.c
src/plugins/rssyl/rssyl_prefs.c
src/plugins/rssyl/rssyl_subscribe.c
src/plugins/rssyl/rssyl_subscribe_gtk.c
src/plugins/rssyl/rssyl_update_comments.c
src/plugins/rssyl/rssyl_update_feed.c
src/plugins/rssyl/rssyl_update_format.c
src/plugins/rssyl/strutils.c
src/plugins/rssyl/tests/strutils_test.c
src/plugins/smime/plugin.c
src/plugins/smime/smime.c
src/plugins/spam_report/spam_report.c
src/plugins/spam_report/spam_report_prefs.c
src/plugins/spamassassin/libspamc.c
src/plugins/spamassassin/spamassassin.c
src/plugins/spamassassin/spamassassin_gtk.c
src/plugins/spamassassin/utils.c
src/plugins/tnef_parse/tnef_dump.c
src/plugins/tnef_parse/tnef_parse.c
src/plugins/vcalendar/common-views.c
src/plugins/vcalendar/day-view.c
src/plugins/vcalendar/month-view.c
src/plugins/vcalendar/plugin.c
src/plugins/vcalendar/vcal_dbus.c
src/plugins/vcalendar/vcal_folder.c
src/plugins/vcalendar/vcal_manager.c
src/plugins/vcalendar/vcal_meeting_gtk.c
src/plugins/vcalendar/vcal_prefs.c
src/plugins/vcalendar/vcalendar.c
src/pop.c
src/prefs_account.c
src/prefs_actions.c
src/prefs_common.c
src/prefs_compose_writing.c
src/prefs_customheader.c
src/prefs_display_header.c
src/prefs_ext_prog.c
src/prefs_filtering.c
src/prefs_filtering_action.c
src/prefs_folder_column.c
src/prefs_folder_item.c
src/prefs_fonts.c
src/prefs_gtk.c
src/prefs_image_viewer.c
src/prefs_logging.c
src/prefs_matcher.c
src/prefs_message.c
src/prefs_migration.c
src/prefs_msg_colors.c
src/prefs_other.c
src/prefs_proxy.c
src/prefs_quote.c
src/prefs_receive.c
src/prefs_send.c
src/prefs_spelling.c
src/prefs_summaries.c
src/prefs_summary_column.c
src/prefs_summary_open.c
src/prefs_template.c
src/prefs_themes.c
src/prefs_toolbar.c
src/prefs_wrapping.c
src/printing.c
src/privacy.c
src/procheader.c
src/procmime.c
src/procmsg.c
src/quote_fmt.c
src/recv.c
src/remotefolder.c
src/send_message.c
src/setup.c
src/sourcewindow.c
src/ssl_manager.c
src/statusbar.c
src/stock_pixmap.c
src/summary_search.c
src/summaryview.c
src/tests/entity_test.c
src/textview.c
src/toolbar.c
src/undo.c
src/uri_opener.c
src/vcard.c
)
Type_Namen=(
AdapterDSource
AdapterFolder
AdapterGroup
AdapterInterface
AddrDupListEntry
AddrItemObject
AddrQueryObject
AddrSelectItem
AddrSelectList
AddressBookFile
AddressCache
AddressClipboard
AddressCvtNode
AddressDataSource
AddressFileSelection
AddressHarvester
AddressIfFragment
AddressIndex
AddressInterface
AddressObject
AddressTypeControlItem
AdvancedSearch
Answer
AttRemover
AttachInfo
AttrKeyValue
AutoConfigureData
AvatarCacheStats
AvatarImageFetch
AvatarRender
Binding
BogoFilterData
BsFilterData
ChildInfo
Children
Clamd_Socket
ClawsSpellEntry
ClawsSpellEntryClass
ClickableText
CodeConverter
ComboboxSelCtx
CommandDataRename
CompletionWindow
Compose
ComposeHeaderEntry
Config
Contact
ContactData
CustomHeader
DBusConnection
DBusContact
DBusGProxy
DBusMessage
DefaultToolbar
DescriptionWindow
Dictionary
DilloViewer
Display
DisplayHeaderProp
ERTFParser
EggModmap
EggVirtualModifierType
EnchantBroker
ExportHtmlCtl
ExportLdifCtl
FILE
FancyPrefsPage
FancyViewer
Feed
FeedAuth
FeedItem
FeedItemEnclosure
FeedParserCtx
Filtering
FilteringAction
FilteringProp
FindAccountInStore
FindAttrInStore
FindNodeByName
FindTagInStore
Folder
FolderClass
FolderColumnState
FolderInfo
FolderItem
FolderItemComposePage
FolderItemGeneralPage
FolderItemPrefs
FolderItemSearch
FolderItemTemplatesPage
FolderItemUpdateData
FolderPathMatch
FolderSortDialog
FolderSortKey
FolderSortType
FolderView
FolderViewPopup
GAsyncResult
GCancellable
GClosure
GDBusConnection
GDBusMethodInvocation
GDataAuthorizer
GDataContactsContact
GDataContactsService
GDataOAuth2Authorizer
GDate
GDateTime
GError
GFile
GHashTable
GIOChannel
GKeyFile
GList
GLogField
GNode
GObject
GPGAccountConfig
GParamSpec
GParamSpecClass
GPtrArray
GSList
GString
GTask
GValue
GVariant
GdkColor
GdkCursor
GdkDragContext
GdkEvent
GdkEventAny
GdkEventButton
GdkEventConfigure
GdkEventCrossing
GdkEventExpose
GdkEventFocus
GdkEventKey
GdkEventMotion
GdkEventScroll
GdkEventVisibility
GdkEventWindowState
GdkKeymap
GdkModifierType
GdkPixbuf
GdkRGBA
GdkScreen
GdkWindow
GdkXEvent
GtkAccelGroup
GtkAction
GtkActionEntry
GtkAdjustment
GtkAllocation
GtkAspell
GtkAspeller
GtkButton
GtkCMCList
GtkCMCTree
GtkCMCTreeNode
GtkCMUnitVtable
GtkCalendar
GtkCellLayout
GtkCellRenderer
GtkCellRendererText
GtkCellRendererToggle
GtkCheckMenuItem
GtkComboBox
GtkComboBoxText
GtkContainer
GtkEditable
GtkEntry
GtkFileChooser
GtkHotkeyInfo
GtkHotkeyKeyFileRegistry
GtkHotkeyKeyFileRegistryClass
GtkHotkeyListener
GtkHotkeyListenerClass
GtkHotkeyRegistry
GtkHotkeyX11Listener
GtkHotkeyX11ListenerClass
GtkImage
GtkLabel
GtkListStore
GtkMenu
GtkMenuItem
GtkMenuShell
GtkNotebook
GtkPageSetup
GtkPaned
GtkPrintContext
GtkPrintOperation
GtkPrintOperationPreview
GtkPrintSettings
GtkRadioAction
GtkRequisition
GtkSHRuler
GtkSHRulerClass
GtkSelectionData
GtkSocket
GtkSpinButton
GtkStatusIcon
GtkStatusbar
GtkStyle
GtkTextBuffer
GtkTextIter
GtkTextTag
GtkTextView
GtkToggleAction
GtkToggleButton
GtkTreeIter
GtkTreeModel
GtkTreePath
GtkTreeSelection
GtkTreeStore
GtkTreeView
GtkTreeViewColumn
GtkUIManager
GtkVScrollbutton
GtkVScrollbuttonClass
GtkWidget
GtkWindow
HeaderEntry
HeaderView
IMAPFolder
IMAPFolderItem
IMAPSearchKey
IMAPSession
IcalFeedData
IcePointer
ImageViewer
IncProgressDialog
IncSession
ItemEMail
ItemFolder
ItemGroup
ItemPerson
JPilotFile
LDAP
LDAPMod
LdapControl
LdapQuery
LdapServer
LdifFile
Ldif_FieldRec
LocalFolder
LogWindow
MMAPString
MainWindow
MatcherList
MatcherProp
MessageView
MessagingMenuApp
MimeInfo
MimeParser
MimeView
MimeViewer
MimeViewerFactory
MsgCache
MsgFlags
MsgInfo
MsgInfoList
MsgInfoUpdate
MsgNumberList
MsgTrash
MuttFile
Mutt_ParsedRec
NewsFolder
NewsGroupInfo
NewsSession
NoticeView
NotificationMsgCount
NotifyNotification
OAUTH2Data
OverlayData
PageResult
PangoColor
ParasitePythonShell
PasswordBlock
PdfViewer
PerlPluginTimedSList
PersonEditDlg
PineFile
Pine_ParsedRec
Plugin
PluginWindow
Pop3Session
PopplerIndexIter
PopplerPage
PopplerRectangle
PrefParam
PrefsAccount
PrefsFilteringActionSignal
PrefsPage
PrefsWindow
PreviewData
PrintData
PrintRenderer
PrivacyData
PrivacySystemSetCtx
ProgressDialog
ProxyInfo
PyObject
QueryRequest
QuickSearch
RFetchCtx
RFolderItem
RSubCtx
Rdn
RemoteFolder
ReportInterface
RsvgHandle
SC_HTMLParser
SC_HTMLTag
SMTPSession
SSL
SSLCertificate
SearchInterface
SelectionResult
SendProgressDialog
Session
SieveCommand
SieveEditorPage
SieveManagerPage
SieveResult
SieveScript
SieveSession
SmPropValue
SnDisplay
SockInfo
SourceWindow
SpecificFolderArrayEntry
StockPixmapData
StringConverter
SummaryColumnState
SummaryView
TNEFStruct
Template
TextView
ThemeInfo
ThemesData
Toolbar
ToolbarItem
ToolbarPage
ToolbarPluginItem
UndoInfo
UndoMain
UserAttribute
VCalAttendee
VCalEvent
VCalMeeting
VCalViewer
VCardFile
WebKitContextMenu
WebKitHitTestResult
WebKitPolicyDecision
WebKitPrintOperation
WebKitURIRequest
WebKitURISchemeRequest
WebKitWebResource
WebKitWebView
WizardWindow
XMLAttr
XMLFile
XMLNode
XMLTag
XML_Char
XML_Encoding
XmlProperty
address_entry
ca_context
cairo_surface_t
cairo_t
carray
chash
chashdatum
chashiter
clawsmail_AccountObject
clawsmail_ComposeWindowObject
clawsmail_FolderObject
clawsmail_FolderPropertiesObject
clawsmail_MailboxObject
clawsmail_MessageInfoObject
clist
clistiter
day_win
gboolean
gchar
gdouble
gint
gpgme_verify_result_t
gpointer
guchar
guint
guint16
guint32
gunichar
icalcomponent
icalproperty
mailimap
mailimf_struct_destructor
mailimf_struct_parser
mailstream
month_win
newsnntp
response
time_t
uint32_t
variableLength
)
Typen=()
for Type_Name in "${Type_Namen[@]}"
do
	: Type_Name ${Type_Name}
	Typen+=( '-T' "${Type_Name}" )
done
indent \
	-linux \
	--line-length1234 \
	--comment-indentation0 \
	--declaration-comment-column0 \
	--line-comments-indentation0 \
	--else-endif-column0 \
	--dont-tab-align-comments \
	--dont-format-comments \
	"${Typen[@]}" \
	"${C_Dateien_mit_Typen[@]}"
for C_Datei in ${C_Dateien_mit_Typen[@]}
do
	sed -i /vim:/d "${C_Datei}"
	cat  >> "${C_Datei}" <<'_Ende_'
/*
 * vim: noet ts=4 shiftwidth=4
 */
_Ende_
done
#
#
#
